package com.yathraCity.core;
// Generated 11 Jan, 2016 10:13:48 AM by Hibernate Tools 3.2.0.CR1



/**
 * ConfirmDriverAvailability generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class ConfirmDriverAvailability  implements java.io.Serializable {


     private Integer id;
     private String driverName;
     private String driverPhoneNumber;
     private String driverLicence;
     private String location;
     private String carNumber;
     private boolean availability;
     private String carType;

    public ConfirmDriverAvailability() {
    }

    public ConfirmDriverAvailability(String driverName, String driverPhoneNumber, String driverLicence, String location, String carNumber, boolean availability, String carType) {
       this.driverName = driverName;
       this.driverPhoneNumber = driverPhoneNumber;
       this.driverLicence = driverLicence;
       this.location = location;
       this.carNumber = carNumber;
       this.availability = availability;
       this.carType = carType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public String getDriverPhoneNumber() {
        return this.driverPhoneNumber;
    }
    
    public void setDriverPhoneNumber(String driverPhoneNumber) {
        this.driverPhoneNumber = driverPhoneNumber;
    }
    public String getDriverLicence() {
        return this.driverLicence;
    }
    
    public void setDriverLicence(String driverLicence) {
        this.driverLicence = driverLicence;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getCarNumber() {
        return this.carNumber;
    }
    
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber;
    }
    public boolean isAvailability() {
        return this.availability;
    }
    
    public void setAvailability(boolean availability) {
        this.availability = availability;
    }
    public String getCarType() {
        return this.carType;
    }
    
    public void setCarType(String carType) {
        this.carType = carType;
    }




}
