package com.yathraCity.core;
// Generated 11 Jan, 2016 10:13:48 AM by Hibernate Tools 3.2.0.CR1



/**
 * CouponDetails generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class CouponDetails  implements java.io.Serializable {


     private Integer id;
     private String coupon;
     private String fromDate;
     private String toDate;

    public CouponDetails() {
    }

    public CouponDetails(String coupon, String fromDate, String toDate) {
       this.coupon = coupon;
       this.fromDate = fromDate;
       this.toDate = toDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCoupon() {
        return this.coupon;
    }
    
    public void setCoupon(String coupon) {
        this.coupon = coupon;
    }
    public String getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }
    public String getToDate() {
        return this.toDate;
    }
    
    public void setToDate(String toDate) {
        this.toDate = toDate;
    }




}
