package com.yathraCity.core;
// Generated 20 Oct, 2015 12:27:33 PM by Hibernate Tools 3.2.0.CR1



/**
 * CoupenDeails generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class CoupenDeails  implements java.io.Serializable {


     private Integer id;
     private String coupen;
     private String fromDate;
     private String toDate;

    public CoupenDeails() {
    }

    public CoupenDeails(String coupen, String fromDate, String toDate) {
       this.coupen = coupen;
       this.fromDate = fromDate;
       this.toDate = toDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCoupen() {
        return this.coupen;
    }
    
    public void setCoupen(String coupen) {
        this.coupen = coupen;
    }
    public String getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }
    public String getToDate() {
        return this.toDate;
    }
    
    public void setToDate(String toDate) {
        this.toDate = toDate;
    }




}
