package com.yathraCity.core;
// Generated 8 Jan, 2016 6:15:46 PM by Hibernate Tools 3.2.0.CR1



/**
 * FetchCarDetails generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class FetchCarDetails  implements java.io.Serializable {


     private Integer id;
     private String registeredAt;
     private String carType;
     private String carNumber;
     private String carModel;

    public FetchCarDetails() {
    }

    public FetchCarDetails(String registeredAt, String carType, String carNumber, String carModel) {
       this.registeredAt = registeredAt;
       this.carType = carType;
       this.carNumber = carNumber;
       this.carModel = carModel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRegisteredAt() {
        return this.registeredAt;
    }
    
    public void setRegisteredAt(String registeredAt) {
        this.registeredAt = registeredAt;
    }
    public String getCarType() {
        return this.carType;
    }
    
    public void setCarType(String carType) {
        this.carType = carType;
    }
    public String getCarNumber() {
        return this.carNumber;
    }
    
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber;
    }
    public String getCarModel() {
        return this.carModel;
    }
    
    public void setCarModel(String carModel) {
        this.carModel = carModel;
    }




}
