package com.yathraCity.core;
// Generated 14 Jan, 2016 9:50:36 AM by Hibernate Tools 3.2.0.CR1



/**
 * ListOfAvailableCars generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class ListOfAvailableCars  implements java.io.Serializable {


     private Integer id;

    public ListOfAvailableCars() {
    }

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }



	private List<RegisterCarInput> car = new ArrayList<RegisterCarInput>();

	@XmlElement
	public List<RegisterCarInput> getCar(){return car;}
	public void setcar (List<RegisterCarInput> arr) {this.car=arr;}


}
