package com.yathraCity.core;
// Generated 20 Oct, 2015 12:27:33 PM by Hibernate Tools 3.2.0.CR1



/**
 * ListOfCoupensUsed generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class ListOfCoupensUsed  implements java.io.Serializable {


     private Integer id;

    public ListOfCoupensUsed() {
    }

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }



	private List<CoupenDeails> listOfCoupens = new ArrayList<CoupenDeails>();

	@XmlElement
	public List<CoupenDeails> getListOfCoupens(){return listOfCoupens;}
	public void setlistOfCoupens (List<CoupenDeails> arr) {this.listOfCoupens=arr;}


}
