package com.yathraCity.core;
// Generated 5 Jan, 2016 10:28:01 AM by Hibernate Tools 3.2.0.CR1



/**
 * RegisterCarResponse generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class RegisterCarResponse  implements java.io.Serializable {


     private Integer id;
     private String message;

    public RegisterCarResponse() {
    }

    public RegisterCarResponse(String message) {
       this.message = message;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}
