package com.yathraCity.core;
// Generated 5 Oct, 2015 10:46:56 AM by Hibernate Tools 3.2.0.CR1



/**
 * RegisterCarDetails generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class RegisterCarDetails  implements java.io.Serializable {


     private Integer id;
     private String carName;
     private String carModel;
     private String carNumber;
     private Integer maximumPeople;
     private String driverName;
     private long phoneNumber;
     private String cityName;
     private Integer minimumDistance;
     private Integer pricePerKm;
     private String driverLicence;

    public RegisterCarDetails() {
    }

    public RegisterCarDetails(String carName, String carModel, String carNumber, Integer maximumPeople, String driverName, long phoneNumber, String cityName, Integer minimumDistance, Integer pricePerKm, String driverLicence) {
       this.carName = carName;
       this.carModel = carModel;
       this.carNumber = carNumber;
       this.maximumPeople = maximumPeople;
       this.driverName = driverName;
       this.phoneNumber = phoneNumber;
       this.cityName = cityName;
       this.minimumDistance = minimumDistance;
       this.pricePerKm = pricePerKm;
       this.driverLicence = driverLicence;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCarName() {
        return this.carName;
    }
    
    public void setCarName(String carName) {
        this.carName = carName;
    }
    public String getCarModel() {
        return this.carModel;
    }
    
    public void setCarModel(String carModel) {
        this.carModel = carModel;
    }
    public String getCarNumber() {
        return this.carNumber;
    }
    
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber;
    }
    public Integer getMaximumPeople() {
        return this.maximumPeople;
    }
    
    public void setMaximumPeople(Integer maximumPeople) {
        this.maximumPeople = maximumPeople;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public long getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Integer getMinimumDistance() {
        return this.minimumDistance;
    }
    
    public void setMinimumDistance(Integer minimumDistance) {
        this.minimumDistance = minimumDistance;
    }
    public Integer getPricePerKm() {
        return this.pricePerKm;
    }
    
    public void setPricePerKm(Integer pricePerKm) {
        this.pricePerKm = pricePerKm;
    }
    public String getDriverLicence() {
        return this.driverLicence;
    }
    
    public void setDriverLicence(String driverLicence) {
        this.driverLicence = driverLicence;
    }




}
