package com.yathraCity.core;
// Generated 4 Oct, 2015 1:21:43 PM by Hibernate Tools 3.2.0.CR1



/**
 * RegisterCarInput generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class RegisterCarInput  implements java.io.Serializable {


     private Integer id;
     private String carName;
     private boolean registered;
     private boolean carAvailability;
     private String carModel;
     private String carNumber;
     private String carOwner;
     private Integer carCapacity;
     private String carRegisteredAt;
     private Integer pricePerKilometer;
     private String ownerLicenseNumber;
     private Integer minimunDistancePerDay;
     private String contactNumber;

    public RegisterCarInput() {
    }

    public RegisterCarInput(String carName, boolean registered, boolean carAvailability, String carModel, String carNumber, String carOwner, Integer carCapacity, String carRegisteredAt, Integer pricePerKilometer, String ownerLicenseNumber, Integer minimunDistancePerDay, String contactNumber) {
       this.carName = carName;
       this.registered = registered;
       this.carAvailability = carAvailability;
       this.carModel = carModel;
       this.carNumber = carNumber;
       this.carOwner = carOwner;
       this.carCapacity = carCapacity;
       this.carRegisteredAt = carRegisteredAt;
       this.pricePerKilometer = pricePerKilometer;
       this.ownerLicenseNumber = ownerLicenseNumber;
       this.minimunDistancePerDay = minimunDistancePerDay;
       this.contactNumber = contactNumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCarName() {
        return this.carName;
    }
    
    public void setCarName(String carName) {
        this.carName = carName;
    }
    public boolean isRegistered() {
        return this.registered;
    }
    
    public void setRegistered(boolean registered) {
        this.registered = registered;
    }
    public boolean isCarAvailability() {
        return this.carAvailability;
    }
    
    public void setCarAvailability(boolean carAvailability) {
        this.carAvailability = carAvailability;
    }
    public String getCarModel() {
        return this.carModel;
    }
    
    public void setCarModel(String carModel) {
        this.carModel = carModel;
    }
    public String getCarNumber() {
        return this.carNumber;
    }
    
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber;
    }
    public String getCarOwner() {
        return this.carOwner;
    }
    
    public void setCarOwner(String carOwner) {
        this.carOwner = carOwner;
    }
    public Integer getCarCapacity() {
        return this.carCapacity;
    }
    
    public void setCarCapacity(Integer carCapacity) {
        this.carCapacity = carCapacity;
    }
    public String getCarRegisteredAt() {
        return this.carRegisteredAt;
    }
    
    public void setCarRegisteredAt(String carRegisteredAt) {
        this.carRegisteredAt = carRegisteredAt;
    }
    public Integer getPricePerKilometer() {
        return this.pricePerKilometer;
    }
    
    public void setPricePerKilometer(Integer pricePerKilometer) {
        this.pricePerKilometer = pricePerKilometer;
    }
    public String getOwnerLicenseNumber() {
        return this.ownerLicenseNumber;
    }
    
    public void setOwnerLicenseNumber(String ownerLicenseNumber) {
        this.ownerLicenseNumber = ownerLicenseNumber;
    }
    public Integer getMinimunDistancePerDay() {
        return this.minimunDistancePerDay;
    }
    
    public void setMinimunDistancePerDay(Integer minimunDistancePerDay) {
        this.minimunDistancePerDay = minimunDistancePerDay;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }




}
