package com.yathraCity.core;
// Generated 8 Jan, 2016 6:15:46 PM by Hibernate Tools 3.2.0.CR1



/**
 * RegisterDriverDetails generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class RegisterDriverDetails  implements java.io.Serializable {


     private Integer id;
     private String driverPhoneNumber;
     private String driverLicence;
     private String driverName;
     private String agencyName;
     private String agencyPhoneNumber;
     private String location;
     private String carNuumber;

    public RegisterDriverDetails() {
    }

    public RegisterDriverDetails(String driverPhoneNumber, String driverLicence, String driverName, String agencyName, String agencyPhoneNumber, String location, String carNuumber) {
       this.driverPhoneNumber = driverPhoneNumber;
       this.driverLicence = driverLicence;
       this.driverName = driverName;
       this.agencyName = agencyName;
       this.agencyPhoneNumber = agencyPhoneNumber;
       this.location = location;
       this.carNuumber = carNuumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDriverPhoneNumber() {
        return this.driverPhoneNumber;
    }
    
    public void setDriverPhoneNumber(String driverPhoneNumber) {
        this.driverPhoneNumber = driverPhoneNumber;
    }
    public String getDriverLicence() {
        return this.driverLicence;
    }
    
    public void setDriverLicence(String driverLicence) {
        this.driverLicence = driverLicence;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public String getAgencyName() {
        return this.agencyName;
    }
    
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName;
    }
    public String getAgencyPhoneNumber() {
        return this.agencyPhoneNumber;
    }
    
    public void setAgencyPhoneNumber(String agencyPhoneNumber) {
        this.agencyPhoneNumber = agencyPhoneNumber;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getCarNuumber() {
        return this.carNuumber;
    }
    
    public void setCarNuumber(String carNuumber) {
        this.carNuumber = carNuumber;
    }




}
