package com.yathraCity.core;
// Generated 4 Oct, 2015 1:21:43 PM by Hibernate Tools 3.2.0.CR1



/**
 * RegisterUser generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class RegisterUser  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String phoneNumber;
     private String userAccountId;
     private String password;

    public RegisterUser() {
    }

    public RegisterUser(String userName, String phoneNumber, String userAccountId, String password) {
       this.userName = userName;
       this.phoneNumber = phoneNumber;
       this.userAccountId = userAccountId;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getUserAccountId() {
        return this.userAccountId;
    }
    
    public void setUserAccountId(String userAccountId) {
        this.userAccountId = userAccountId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}
