package com.yathraCity.core;
// Generated 5 Oct, 2015 10:46:56 AM by Hibernate Tools 3.2.0.CR1



/**
 * TotalNumberOfUsers generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class TotalNumberOfUsers  implements java.io.Serializable {


     private Integer id;
     private Integer count;

    public TotalNumberOfUsers() {
    }

    public TotalNumberOfUsers(Integer count) {
       this.count = count;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }




}
