package defaultpkg;
import com.razorthink.runtime.*;
public class ErrorCodes  {
	public static ErrorStatus APPLICATION_ERROR = new ErrorStatus(500,"APPLICATION_ERROR","SERVICE_MAIN","ERR500","","","","Application Error Occured in primary thread");
	public static ErrorStatus INVALID_EMAIL_ID = new ErrorStatus(400,"INVALID_EMAIL_ID","","ERR_100","","Enter Valid emailId","","Invalid Parameter");
	public static ErrorStatus INVALID_MESSAGE_UID = new ErrorStatus(400,"INVALID_MESSAGE_UID","","ERR_101","messageUID","Enter Valid messageUID","","Invalid Parameter");
	public static ErrorStatus INVALID_NUMBER_OF_RESULTS_TO_RETURN = new ErrorStatus(400,"INVALID_NUMBER_OF_RESULTS_TO_RETURN","","ERR_102","numOfResultsToReturn","Enter Valid numOfResultsToReturn","","Invalid Parameter");
	public static ErrorStatus INVALID_FOLDERNAME = new ErrorStatus(400,"INVALID_FOLDERNAME","","ERR_103","folder","Enter Valid folderName","","Invalid Parameter");
	public static ErrorStatus INVALID_TAG = new ErrorStatus(400,"INVALID_TAG","","ERR_115","folder","Enter Valid Tag","","Invalid Parameter");
	public static ErrorStatus INVALID_BUCKETLABEL = new ErrorStatus(400,"INVALID_BUCKETLABEL","","ERR_115","bucketLabel","Enter Valid bucketLabel","","Invalid Parameter");
	public static ErrorStatus INVALID_LONGVALUE = new ErrorStatus(400,"INVALID_LONGVALUE","","ERR_116","bucketLabel","Enter Valid snoozedAt value","","Invalid Parameter");
	public static ErrorStatus INVALID_FILENAME = new ErrorStatus(400,"INVALID_FILENAME","","ERR_104","file_Attachment","Attachment filePath while sending mail","","Invalid Parameter");
	public static ErrorStatus INVALID_STATUS = new ErrorStatus(400,"INVALID_STATUS","","ERR_105","status","Enter Valid Status","","Invalid Parameter");
	public static ErrorStatus INVALID_MAILPROVIDER = new ErrorStatus(400,"INVALID_MAILPROVIDER","","ERR_106","mailProvider","Enter Valid mailProvider","","Invalid Parameter");
	public static ErrorStatus MISSING_FIELD = new ErrorStatus(400,"MISSING_FIELD","","ERR_107","","Enter All the Mandatory fields","","Missing field/s");
	public static ErrorStatus BAD_REQUEST = new ErrorStatus(400,"BAD_REQUEST","","ERR_108","","Check the input","","Bad request");
	public static ErrorStatus USER_ALREADY_EXISTS = new ErrorStatus(400,"USER_ALREADY_EXISTS","","ERR_109","","Duplicate entry","","User already added");
	public static ErrorStatus INVALID_ID = new ErrorStatus(400,"INVALID_ID","","ERR_110","","Enter Valid UUID format","","Enter valid ids(UUID)");
	public static ErrorStatus INVALID_ACTION = new ErrorStatus(400,"INVALID_ACTION","","ERR_111","status","Enter either add or remove action","","Invalid Parameter");
	public static ErrorStatus INVALID_VALUE = new ErrorStatus(400,"INVALID_VALUE","","ERR_112","status","Enter either true or false","","Invalid Parameter");
	public static ErrorStatus INVALID_INBLOX_USER_ID = new ErrorStatus(400,"INVALID_INBLOX_USER_ID","","ERR_116","status","primary account mismatch","","Invalid primary account");
	public static ErrorStatus SIMULTANEOUS_CONNECTIONS = new ErrorStatus(400,"SIMULTANEOUS_CONNECTIONS","","ERR_115","status","Too many simultaneous connections","","Too many simultaneous connections");
	public static ErrorStatus INVALID_SESSION_TOKEN = new ErrorStatus(400,"INVALID_SESSION_TOKEN","","ERR_120","status","couldn't find the provided inblox user id","","inblox user id not found");
	public static ErrorStatus INVALID_DEVELOPER_KEY = new ErrorStatus(400,"INVALID_DEVELOPER_KEY","","ERR_121","status","couldn't find the provided inblox user id","","inblox user id not found");
	public static ErrorStatus RECORD_NOT_FOUND = new ErrorStatus(404,"RECORD_NOT_FOUND","","ERR_113","","No record found","","No record found");
	public static ErrorStatus USER_NOT_FOUND = new ErrorStatus(404,"USER_NOT_FOUND","","ERR_114","","User not found","","user not registered");
	public static ErrorStatus INBLOX_USER_ID_NOT_FOUND = new ErrorStatus(404,"INBLOX_USER_ID_NOT_FOUND","","ERR_117","status","couldn't find the provided inblox user id","","inblox user id not found");
	public static ErrorStatus ACTIVE_SESSION_TOKEN_NOT_FOUND = new ErrorStatus(404,"ACTIVE_SESSION_TOKEN_NOT_FOUND","","ERR_118","status","request for a new session token","","no active session token for the requested user");
	public static ErrorStatus DEVELOPER_KEY_NOT_FOUND = new ErrorStatus(404,"DEVELOPER_KEY_NOT_FOUND","","ERR_122","status","request for a new session token","","no active session token for the requested user");
	public static ErrorStatus MANDATORY_HEADER_NOT_FOUND = new ErrorStatus(404,"MANDATORY_HEADER_NOT_FOUND","","ERR_119","status","","","one of the mandatory header fields is not found");
	public static ErrorStatus SUCCESS = new ErrorStatus(200,"SUCCESS","","SUCCESS_200","status","","","one of the mandatory header fields is not found");
}
