package com.yathraCity.services.config;



/**
 * StringClass generated by hbm2java
 */
import javax.xml.bind.annotation.*;
import java.util.*;
@XmlRootElement
public class StringClass  implements java.io.Serializable {


     private Integer id;
     private String value;

    public StringClass() {
    }

    public StringClass(String value) {
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}
